services:
  # Backend service
  - type: web
    name: slightedgesales-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend service  
  - type: web
    name: slightedgesales-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://slightedgesales-frontend.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin